Brandon detail search
vitzlo/rocket-mart-web-app pull request #7
Opened 2023-11-27 05:43 UTC by xiushak

2023-11-29 22:26 UTC, vitzlo requested changes
Some questions/suggestions, looks swag

2023-11-29 22:26 UTC, vitzlo commented on src/Pokemon/SmallView/index.js
> +          {pokemonData.name.replaceAll("-", " ")}
do we wanna just do this in the prune at this point, and have it as an invariant

2023-11-29 22:26 UTC, vitzlo commented on src/SearchResults/index.js
> +    setSearchResults([]);
is this necessary? i commented it out and the rendering seems to work fine but if there's a reason for this being here then it's chill

2023-11-29 22:26 UTC, vitzlo commented on src/SearchResults/index.js
> +              src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2FS0dlRVeqjpoTC%2Fgiphy.gif&f=1&nofb=1&ipt=1fcd67f50a18eb323cb536b60a98d4543333c563cdea04fae3c1a
https://media.giphy.com/media/S0dlRVeqjpoTC/giphy.gif seems better

2023-11-29 22:26 UTC, vitzlo commented on src/SearchResults/index.js
> +              src="https://i0.wp.com/media1.giphy.com/media/dJYoOVAWf2QkU/giphy.gif?resize=640%2C640&ssl=1&crop=1"
https://media.giphy.com/media/12Bpme5pTzGmg8/giphy.gif seems better

2023-11-29 22:26 UTC, vitzlo commented on src/SearchResults/index.js
> +              src="https://i0.wp.com/media1.giphy.com/media/dJYoOVAWf2QkU/giphy.gif?resize=640%2C640&ssl=1&crop=1"
its not square tho so idk

2023-11-29 22:35 UTC, xiushak commented on src/Pokemon/SmallView/index.js
> +          {pokemonData.name.replaceAll("-", " ")}
i decided to only include the replace when displaying the name in case we had to use the name to lookup a Pokemon later

2023-11-29 22:36 UTC, xiushak commented on src/SearchResults/index.js
> +    setSearchResults([]);
the loading screen won't show if this isn't included

2023-11-30 23:36 UTC, vitzlo approved these changes
lgtm

2023-11-30 23:37 UTC, merged